#!/usr/bin/env python3
"""CEE+ headless single-run pipeline.

Runs the same Stage-1 analysis as the Dash UI's Analyze + Export buttons,
without needing the browser. Useful for remote use (SSH from phone) and
scripted batches.

Examples:

    # One image, inline caption.
    python run_pipeline.py --image experiments/exp2/images/1.jpg \
        --caption-text "A flooded road and a man on a car"

    # One image, caption auto-generated by the VLM.
    python run_pipeline.py --image experiments/exp2/images/1.jpg

    # First image in a folder.
    python run_pipeline.py --image experiments/exp2/images

    # Nth image in a folder.
    python run_pipeline.py --image experiments/exp2/images --index 3

    # Every image in a folder, sequentially.
    python run_pipeline.py --image experiments/exp2/images --all

    # Just list what's in a folder, don't run.
    python run_pipeline.py --image experiments/exp2/images --list

Caption priority (highest wins):
    1. --caption-text "..."
    2. --caption-file PATH
    3. Sidecar text file next to image (e.g. 1.txt next to 1.jpg)
    4. caption.txt in the same folder as the image
    5. VLM-generated caption (default fallback)

Output:
    Each run produces exports/runs/run_<timestamp>/ containing
    structured_response.json, prompt.txt, caption.txt, and the source image,
    identical to what the UI's Export Result button writes.
"""

from __future__ import annotations

import argparse
import base64
import json
import mimetypes
import os
import sys
from datetime import datetime
from pathlib import Path
from typing import Any
import os as _os

import requests

# Importing main constructs the Dash app object, but we never start its server.
from main import (
    DEFAULT_PROMPT,
    EXPORT_ROOT,
    PLACEHOLDER_RESULT,
    PATHOLOGY_REGISTRY,
    assess_pre_intervention_trust,
    compare_graphs,
    detect_pathologies,
    query_qwen,
    query_qwen_graph_b,
    safe_filename,
)

IMG_EXTS = {".jpg", ".jpeg", ".png", ".webp"}


def _list_images(target: Path, recurse: bool = False) -> list[Path]:
    if target.is_file():
        return [target]
    if target.is_dir():
        if recurse:
            # os.walk with followlinks=True so symlinked subfolders (e.g.
            # batch_input/fire -> ../exp2/images/fire) are traversed.
            found: list[Path] = []
            for root, _dirs, files in _os.walk(target, followlinks=True):
                for name in files:
                    p = Path(root) / name
                    if p.suffix.lower() in IMG_EXTS:
                        found.append(p)
            return sorted(found)
        return sorted(p for p in target.iterdir() if p.suffix.lower() in IMG_EXTS)
    raise FileNotFoundError(target)


def _encode_image(path: Path) -> str:
    mime = mimetypes.guess_type(str(path))[0] or "image/jpeg"
    b64 = base64.b64encode(path.read_bytes()).decode("ascii")
    return f"data:{mime};base64,{b64}"


def _auto_caption(image_data_url: str) -> str:
    """One-shot VLM call to produce a short scene caption."""
    api_url = os.getenv("QWEN_API_URL", "http://localhost:11434/v1/chat/completions")
    api_key = os.getenv("QWEN_API_KEY", "")
    model = os.getenv("QWEN_MODEL_NAME", "qwen2.5vl:7b")
    headers = {"Content-Type": "application/json"}
    if api_key:
        headers["Authorization"] = f"Bearer {api_key}"
    body = {
        "model": model,
        "messages": [
            {
                "role": "user",
                "content": [
                    {
                        "type": "text",
                        "text": (
                            "Describe this scene in one short, concrete sentence "
                            "(under 20 words). No commentary, no preamble."
                        ),
                    },
                    {"type": "image_url", "image_url": {"url": image_data_url}},
                ],
            }
        ],
        "temperature": 0.0,
    }
    r = requests.post(api_url, headers=headers, json=body, timeout=60)
    r.raise_for_status()
    msg = r.json()["choices"][0]["message"]["content"]
    if isinstance(msg, list):
        msg = "\n".join(p.get("text", "") for p in msg if isinstance(p, dict))
    return str(msg).strip()


def _resolve_caption(args: argparse.Namespace, image_path: Path, image_data_url: str) -> tuple[str, str]:
    """Return (caption, source) by priority order. Empty string if nothing found."""
    if args.caption_text is not None:
        return args.caption_text, "inline"
    if args.caption_file:
        return Path(args.caption_file).expanduser().read_text(encoding="utf-8").strip(), "file"
    sidecar = image_path.with_suffix(".txt")
    if sidecar.exists():
        return sidecar.read_text(encoding="utf-8").strip(), f"sidecar({sidecar.name})"
    folder_cap = image_path.parent / "caption.txt"
    if folder_cap.exists():
        return folder_cap.read_text(encoding="utf-8").strip(), "folder(caption.txt)"
    if args.no_auto_caption:
        return "", "empty"
    return _auto_caption(image_data_url), "vlm"


def _run_one(image_path: Path, args: argparse.Namespace) -> Path:
    print(f"\n=== {image_path} ===", flush=True)
    image_data_url = _encode_image(image_path)

    caption, source = _resolve_caption(args, image_path, image_data_url)
    print(f"Caption [{source}]: {caption!r}", flush=True)

    prompt = DEFAULT_PROMPT

    print("Graph A (recommendations) …", flush=True)
    result: dict[str, Any] = query_qwen(prompt, caption, image_data_url, allow_inferred=False)
    run_id = datetime.now().strftime("run_%Y%m%dT%H%M%S")
    result["run_id"] = run_id
    result["image_filename"] = safe_filename(image_path.name)
    result["allow_inferred"] = False

    print("Graph B (independent causal graph) …", flush=True)
    try:
        graph_b = query_qwen_graph_b(
            result["detected_objects"],
            result["threats"],
            caption,
            image_data_url,
            allow_inferred=False,
        )
        result["graph_b"] = graph_b
        result["graph_consistency"] = compare_graphs(result["causal_graph"], graph_b)
        result["pre_intervention_trust"] = assess_pre_intervention_trust(
            result.get("pre_internal_alignment", {}),
            result["graph_consistency"],
            result["causal_graph"],
            graph_b,
        )
        result["pathologies"] = detect_pathologies(
            result["graph_consistency"],
            result.get("recommendations", []),
            result["causal_graph"],
            result["pre_intervention_trust"],
        )
    except Exception as exc:
        print(f"  Graph B failed: {exc}", flush=True)
        result["graph_b"] = dict(PLACEHOLDER_RESULT["graph_b"])

    # Mirror the UI's Export Result layout: exports/runs/run_<ts>/
    exported_at = datetime.now().strftime("%Y-%m-%dT%H-%M-%S")
    run_dir = EXPORT_ROOT / "runs" / run_id
    run_dir.mkdir(parents=True, exist_ok=True)

    # Copy image bytes in (the UI export does the same).
    out_image_name = safe_filename(image_path.name)
    if "." not in out_image_name:
        out_image_name += image_path.suffix or ".jpg"
    (run_dir / out_image_name).write_bytes(image_path.read_bytes())

    payload = {
        "exported_at": exported_at,
        "run_id": run_id,
        "model": os.getenv("QWEN_MODEL_NAME", "qwen2.5vl:7b"),
        "image_filename": result["image_filename"],
        "prompt": prompt,
        "caption": caption,
        "structured_response": result,
    }
    (run_dir / "structured_response.json").write_text(json.dumps(payload, indent=2))
    (run_dir / "prompt.txt").write_text(prompt)
    (run_dir / "caption.txt").write_text(caption)

    # Compact summary
    trust = result.get("pre_intervention_trust") or {}
    gc = result.get("graph_consistency") or {}
    align = result.get("pre_internal_alignment") or {}
    paths = result.get("pathologies") or {}
    active = paths.get("active_keys") or []
    print(f"  Trust:               {trust.get('level','?'):<10} {trust.get('score',0):.2f}", flush=True)
    print(f"  A-fidelity:          {gc.get('a_fidelity',0):.2f}", flush=True)
    print(f"  B-coverage:          {gc.get('b_coverage',0):.2f}", flush=True)
    print(f"  Internal alignment:  {align.get('score',1):.2f} ({align.get('passed_checks',0)}p / {align.get('failed_checks',0)}f)", flush=True)
    if active:
        labels = [PATHOLOGY_REGISTRY[k]["label"] for k in active if k in PATHOLOGY_REGISTRY]
        print(f"  Pathologies fired:   {', '.join(labels)}", flush=True)
    else:
        print("  Pathologies fired:   none", flush=True)
    print(f"  Saved → {run_dir}", flush=True)
    return run_dir


def _parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="CEE+ headless single-run pipeline.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument("--image", required=True, help="Image file or folder containing images.")
    p.add_argument("--recurse", action="store_true", help="(folder) Walk subfolders for images. Use for nested batch_input/.")
    sel = p.add_mutually_exclusive_group()
    sel.add_argument("--index", type=int, help="(folder) Use the Nth image (0-based, default 0).")
    sel.add_argument("--all", action="store_true", help="(folder) Run on every image, sequentially.")
    sel.add_argument("--list", action="store_true", dest="list_only", help="(folder) Just list images and exit.")

    cap = p.add_mutually_exclusive_group()
    cap.add_argument("--caption-text", help="Inline caption text. Use empty string for no caption.")
    cap.add_argument("--caption-file", help="Path to a caption text file.")
    cap.add_argument(
        "--no-auto-caption",
        action="store_true",
        help="Skip VLM caption generation. Falls back to empty caption if no sidecar/folder caption found.",
    )
    return p.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = _parse_args(argv)
    target = Path(args.image).expanduser().resolve()
    try:
        images = _list_images(target, recurse=args.recurse)
    except FileNotFoundError:
        print(f"Path not found: {target}", file=sys.stderr)
        return 2
    if not images:
        print(f"No images at {target}", file=sys.stderr)
        return 2

    if args.list_only:
        print(f"{len(images)} image(s) in {target}:")
        for i, p in enumerate(images):
            print(f"  [{i}] {p.name}")
        return 0

    if target.is_dir():
        if args.all:
            selection = images
        else:
            idx = args.index or 0
            if idx < 0 or idx >= len(images):
                print(f"--index {idx} out of range (0..{len(images)-1})", file=sys.stderr)
                return 2
            selection = [images[idx]]
    else:
        selection = images

    rc = 0
    for img in selection:
        try:
            _run_one(img, args)
        except Exception as exc:
            print(f"FAILED {img.name}: {exc}", file=sys.stderr, flush=True)
            rc = 1
    return rc


if __name__ == "__main__":
    sys.exit(main())
